

# Preface

## Selling and buying process:

### Salespeople skill/ preception 

include the intuition/ first impression, price importance sensing.
salespeople skill vs. adaptive selling, SOCO.

[@spiro1990]

Adaptive selling: conceptualization, measurement, and nomological
validity

Introduce the skill of adaptive selling. even thought all adapt, but to
what extent is not clear. how effective is not clear.

A 16-item scale is developed to measure the degree to which salespeople
practice
adaptive selling-the degree to which they alter their sales presentation
across and
during customer interactions in response to the perceived nature of the
sales situ-
ation. This paper-and-pencil scale assesses self-reports of five facets
of adaptive
selling: (1) recognition that different sales approaches are needed for
different cus-
tomers, (2) confidence in ability to use a variety of approaches, (3)
confidence in
ability to alter approach during an interaction, (4) collection of
information to fa-
cilitate adaptation, and (5) actual use of different approaches. The
reliability of
the scale is .85. Support for the nomological validity of the scale is
found by failure
to disconfirm relationships with an antecedent (intrinsic motivation),
several general
personality measures of interpersonal flexibility (self-monitoring,
empathy, locus of
control, and androgyny), and a consequence (self-reported perfo

[@mullins2014]

Know Your Customer: How
Salesperson Perceptions of
Customer Relationship Quality Form
and Influence Account Profitability

salespeople's skill in sense the customer impacts the account profit

Firms often utilize salesperson intelligence in marketing strategies to
improve sales performance. However, this
approach is problematic if the information is based on inaccurate
perceptions. In light of this, the authors introduce
a theoretical model to study the antecedents and profit impact of
salesperson perceptions of customer relationship
quality. Dyadic analyses using matched survey responses from
salesperson--customer dyads and secondary
performance data reveal several insightful findings. Results show that
self-efficacious salespeople are upwardly
biased, whereas customer-oriented salespeople are downwardly biased in
their perceptions of customer
relationship quality. However, managers can correct these inaccuracies
using a behavior-based control system.
Response surface analyses illustrate that the effects of salesperson
accuracy and inaccuracy are distinct and
curvilinear. During later relationship phases, salespeople profit more
from salesperson accuracy in high- and lowquality relationships (i.e.,
a U-shaped effect). Yet the increasingly harmful impact of salesperson
inaccuracy on
profit is more severe during earlier relationship phases. Together,
these findings highlight the benefits of measuring
salesperson perceptions and how to manage them

[@romanavila2010]

Antecedents and consequences of adaptive selling confidence and
behavior: a dyadic analysis of salespeople and their customers

antecdent and consequence of adaptive selling

Personal selling is thought to be a very effective marketing vehicle.
The notion of adaptive selling suggests that it should work better than
any other means of communication because salespeople are able to develop
a unique message for each customer. This research proposes a model of
key antecedents and consequences of adaptive selling. In particular, we
distinguish, measure, and model the attitudinal and behavioral aspects
of adaptive selling, something that is encouraged but not thoroughly
examined in the literature. Hypotheses are tested using data from 210
salesperson-customer dyads. The results indicate that a salesperson's
perception of the firm's customer orientation has an effect on adaptive
selling behavior through the salesperson's adaptive selling confidence,
role ambiguity, intrinsic motivation and customer-qualification skills.
Adaptive selling behavior increases salesperson's outcome performance,
customers' evaluations of satisfaction with the product and with the
salesperson, which enhance customers' anticipation of future
interactions with the salesperson. The implications for management and
theory are discussed.

### Communication - intraorganization

[@johlke2000]

Sales manager's impact on the salesperson job outcomes

drawing from several diverse streams of research, the authors develop
the rationale and empirical background for considering the role of sales
manager communication practices. Using a multifaceted conceptualization
of communication as its base, the study justifies, proposes, and
evaluates a model describing the relations among sales
managers'communication practices and salesperson ambiguity,
satisfaction, performance, and commitment. The results support the
hypothesized model and suggest that sales manager communication
practices are associated with these important salesperson job outcomes.

[@bolander2015]

Social Networks Within Sales Organizations: Their Development
and Importance for Salesperson Performance

Salespeople's communication among peers on their job performance

Although the study of salesperson performance traditionally has focused
on salespeople's activities and relationships
with customers, scholars recently have proposed that salespeople's
intraorganizational relationships and activities
also play a vital role in driving sales performance. Using data from 286
salespeople in a unique social network analysis,
the authors explore the effects of salespeople's intraorganizational
relationships on objective salesperson performance
as well as the role of political skill in developing intraorganizational
relationships. The results indicate that two types of
social network characteristics (i.e., relational centrality and
positional centrality) contribute substantially to salesperson
performance. Moreover, salespeople's political skill is shown to be an
antecedent to relational centrality but, surprisingly,
not positional centrality. This finding demonstrates that researchers
should not assume that all centralities represent
similar underlying network characteristics. In light of these results,
the authors discuss several implications for both
managers and researchers as well as directions for further research

### Communication Interorganization - customer 

[@boorom1998]

Relational Communication Traits and Their Effect on Adaptiveness and
Sales Performance

How does the salesperson trait affects the communication effectiveness
and then on the job performance.

Two relational communication traits, communication apprehension and
interaction involvement, are investigated
within an adaptive selling framework to assess their impact on
salesperson adaptiveness and sales performance.
Using a sample of 239 insurance salespeople, results
demonstrate that salespeople exhibiting lower levels of
communication apprehension are more highly involved in
communication interactions, and higher involvement facilitates
increased adaptiveness and sales performance.
This research highlights the importance of effective communication
within sales interactions and offers suggestions to improve salesperson
communication skill

[@soldow1984]

Relational Communication: Form versus Content in the Sales Interaction

two type of f2f comm: content and relationship

In view of the importance of interpersonal com-
munication in the face-to-face selling interaction,
this discussion seeks to provide a more complete
picture of the actual communication process by
introducing a concept new to the marketing liter-
ature. The concept is relational communication,
which refers to that part of a message beyond the
actual content which allows communicators to ne-
gotiate their relative positions. Thus, the message
sender can either bid for dominance, deference,
or equality. The message receiver, in turn, can ac-
cept the bid or deny

### Sales marketing interface

[@smith2006]

A Three-Stage Model of Integrated Marketing
Communications at the Marketing--Sales
Interface

The marketing and sales functions in many firms are often at odds
despite their common goal of increasing revenue and profit. The finger
pointing goes both ways: Marketing complains of poor lead follow-up by
sales, and in turn, sales grumbles about the quality of leads generated
by
marketing. This disconnect can be damaging; high lead volumes
generated through effective marketing campaigns could actually hurt
downstream sales because of wasted effort on poorly qualified leads
and/or delays in sales follow-up resulting from limited sales force
capacity. To examine the revenue and profit implications of coordinated
communications efforts at the marketing--sales interface, the authors
develop a three-stage model that captures the effects of sequential
marketing/sales communications on lead generation, appointment
conversion, and sales closure. The results, which are based on a
collaborative effort with a large home improvement retailer, suggest a
complex interplay among marketing efforts (multiple media that generate
leads), delays in follow-up (time lag between inquiry and sales force
contact), and sales efficiencies (appointment and sales conversion). The
findings underscore the impact of multimedia spending on the timing and
effectiveness of subsequent communications, implying that improved
internal collaboration between marketing and sales can offer significant
upside potential for the firm. Finally, the authors develop a managerial
decision support tool to simulate the impact of varying communications
budgets, timing, and allocation on the marketing and sales planning
system.

### Firm level impact on salespeople

[@salonen2020a]

Engaging a product-focused sales force in solution selling: interplay
of individual- and organizational-level conditions
Solution selling transform from product focused selling .

This study explains how manufacturers tackle the critical managerial
challenge of transforming a product-focused sales force to
undertake solution selling. Through an application of configurational
theory, the authors explain how individual and organizational
conditions combine to determine salespeople's engagement in solution
selling. Multilevel, multisource data from the sales
organization of a global supplier of building solutions represent input
from salespeople (N = 184), solution champions (N = 23),
and sales managers (N = 26). A fuzzy set qualitative comparative
analysis reveals no single, optimal way to overcome transformation
challenges. Rather, consistent with prior research, solution selling
requires certain types of salespeople, because valuebased selling is a
necessary condition for successful engagement. Beyond this foundational
condition, a heterogeneous sales force
can be engaged, as long as the organization provides appropriate support
that is tailored to individual salespersons' needs. The
findings affirm that this viable support can come from either sales
managers or solution champions

[@smith1997]

The Effects of Organizational Differences and Trust on the Effectiveness
of Selling
Partner Relationships

organizational level selling together

Selling alliances that are formed to cooperatively develop and maintain
customer relationships are among the new
organizational forms that marketing managers utilize for competitive
advantage. To be successful, these alliances
require sales representatives from allied organizations to work
effectively as selling partners. The authors develop
a trust-based model of effective selling partner relationships and test
it in the context of the computer industry. Par-
tial Least Squares analysis of 103 dyadic relationships found that
organizational differences were modest predic-
tors of three dimensions of mutual perceived trustworthiness, which in
turn differentially affected three trusting
behaviors. Trusting behaviors were found to have a somewhat greater
effect on perceived task performance than
on mutual satisfaction, whereas dimensions of trustworthiness had both
direct and indirect effects on satisfaction.
The authors discuss the managerial and theoretical implications of th

### Salesperson trait orientation 

[@kidwell2011]

Emotional Intelligence in Marketing
Exchanges

EQ's impact on the sales performance

This research examines how sales professionals use emotions in marketing
exchanges to facilitate positive
outcomes for their firms, themselves, and their customers. The authors
conduct three field studies to examine the
impact of emotional intelligence (EI) in marketing exchanges on sales
performance and customer relationships.
They find that EI is positively related to performance of real estate
and insurance agents, even when controlling for
the effects of domain-general EI, self-report EI, cognitive ability, and
several control variables. Sales professionals
with higher EI are not only superior revenue generators but also better
at retaining customers. In addition, the
authors demonstrate that EI interacts with key marketing exchange
variables---customer orientation and manifest
influence---to heighten performance such that high-EI salespeople more
effectively employ customer-oriented
selling and influence customer decisions. Finally, the results indicate
a complementary relationship between EI and
cognitive ability in that EI positively influences performance at higher
levels of cognitive ability. These findings have
implications for improving interactions between buyers and sellers and
for employee selection and training

[@mcfarland2015]

Moderator of the EQ's effect on job outcomes

A contingency model of emotional intelligence
in professional selling
Abstract Despite significant attention from practitioners
and broad claims of the importance of Emotional
Intelligence (EI), empirical support for its incremental
direct effects on outcomes relevant to professional selling has been
disappointing. However, little research has
included relevant contextual variables or the potential
interactions of EI with contextual variables when considering its
effects. This contingency view of EI maintains that EI is important in
work settings, but only
under certain conditions. Drawing on the appraisal theory of emotions,
the authors develop a contingency
model, which proposes that salesperson EI moderates
the harmful effects of role stress on three work outcomes---emotional
exhaustion, customer-oriented selling,
and sales performance. Using three matched data sources from
multiple professional selling workgroups in a business-tobusiness sales
setting, the authors find that EI moderates the relationship between
role ambiguity and all three outcome
variables.



[@lam2019]

**Salesperson ambidexterity in customer engagement: do customer base
characteristics matter?**

salesperson orientation moderated by customer base on sales performance

This research examines how sales professionals use emotions in marketing
exchanges to facilitate positive
outcomes for their firms, themselves, and their customers. The authors
conduct three field studies to examine the
impact of emotional intelligence (EI) in marketing exchanges on sales
performance and customer relationships.
They find that EI is positively related to performance of real estate
and insurance agents, even when controlling for
the effects of domain-general EI, self-report EI, cognitive ability, and
several control variables. Sales professionals
with higher EI are not only superior revenue generators but also better
at retaining customers. In addition, the
authors demonstrate that EI interacts with key marketing exchange
variables---customer orientation and manifest
influence---to heighten performance such that high-EI salespeople more
effectively employ customer-oriented
selling and influence customer decisions. Finally, the results indicate
a complementary relationship between EI and
cognitive ability in that EI positively influences performance at higher
levels of cognitive ability. These findings have
implications for improving interactions between buyers and sellers and
for employee selection and training

### Salesperson non-sales activity/ service

[@johnson2015]

Understanding and resolving major contractual breaches
in buyer--seller relationships: a grounded theory approach

Abstract In business-to-business relationships, sellers are often faced
with instances of contractual breaches by buyers. In
many cases, relationship factors preclude legal enforcement of
contract terms, requiring sellers to explore alternate resolution
options. Literature on contractual breaches has primarily focused on
enforcement options based on terms specified in the
contract. However, little is known about how companies deal
with contractual breaches by their customers when legal enforcement is
not a viable option. The authors use a grounded
theory approach to investigate this important issue. Based on
in-depth interviews with 40 supplier managers and executives
in multiple industries, the authors identify: (a) types of
out-ofcontract alternatives for resolving breaches, (b) factors
that lead to use of enforcement options outside the terms
specified in the contract, (c) contextual influences, and (d)
individual and firm-level consequences of outside-ofcontract
enforcement.

[@malshe2018a]

Initiating value co-creation: Dealing with non-receptive customers

deal with co-creation reluctance. co-creation to improve the offering.

Scholarly emphasis on the significance of integrating customer and
supplier work processes to co-create customer value is increasingly
important. While suppliers and customers working closely is imperative
for the success of the value co-creation (VCC) process, customers'
reluctance at times to allow suppliers into their environments has not
been fully explored. The present study is an expansive qualitative
inquiry consisting of 114 in-depth interviews across 57
business-to-business evaluations that aims to understand both the
nuanced nature of customer non-receptivity to specific VCC initiatives
and those strategies suppliers may adopt to successfully manage it.
Findings elicit three potential kinds of customer non-receptivity:
apathy, ambivalence, and annoyance. Furthermore, conclusions propose six
strategies suppliers may use to manage customer non-receptivity:
intrinsic initiative, inspiration and implementation, complexity
absorption, value alignment, credibility building, and objective
centrality.

[@panagopoulos2017]

Salesperson Solution Involvement
and Sales Performance: The
Contingent Role of Supplier Firm and
Customer--Supplier
Relationship Characteristics

salespeople invovled in the solution (not solution selling)'s impaact on
the long term performance

Salespeople play a crucial role in their firms' efforts to provide
customer solutions. However, little research has
examined how salesperson involvement in customer solutions can be
conceptualized, whether it pays off, and what
boundary conditions might heighten its performance effects. This study
addresses these gaps and offers a
conceptualization of salesperson solution involvement by focusing on the
set of salesperson-related activities that
enact the four relational processes inherent in customer solutions. The
authors collect a unique data set that includes a
wide range of firms, industries, and countries, as well as the
perspectives of both salespeople and customers, across
five studies. Results validate the stability of the conceptualization
across contexts. They also reveal that salesperson
solution involvement is systematically related to increases in both
subjective and objective, time-lagged measures
of sales performance. Finally, results show that the performance effects
of salesperson solution involvement
are amplified under higher levels of firm's product portfolio scope,
sales unit cross-functional cooperation, and
customer--supplier relationship tie strength. Surprisingly, customer
adaptiveness is not found to moderate the
performance effects of salesperson solution involvement.

### B2G 

[@chase2019]

In business-to-government and business-to-business transactions,
suppliers often have limited access to buyers during the buying
process. The authors term these buyers "barricaded buyers." Despite the
prevalence of barricaded buyers in practice, research
has remained largely silent on the topic. Therefore, the authors combine
insights from eight organizational purchasing case studies
and individual interviews with signaling theory to advance a conceptual
framework that highlights ways a supplier can increase its
competitiveness (and, correspondingly, its selection likelihood) when
selling to barricaded buyers. The framework reflects three
distinct ways in which signaling occurs or influences the barricaded
buying process: the seller signals to buyers (e.g., through novel
solutions, explicit responding), the seller signals to competing sellers
(e.g., through peacocking), and the buyer signals to sellers
whose meaning is jammed (e.g., through supplier-specific capabilities
and language). The framework invokes barricade restrictiveness as an
important contingency variable that lends nuance to when the signaling
activities are most likely to affect suppliers'
competitiveness.
